---
- name: do some debugging
  ansible.builtin.debug:
    msg: '{{ user_homedir }}/Pictures'
  tags: never, debug

- name: Add microsoft.asc key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Microsoft repo
  ansible.builtin.apt_repository:
    repo: deb-src https://packages.microsoft.com/repos/code stable main
    state: present

- name: packages are present
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
    update_cache: true
  loop: '{{ system_apps }}'

- name: Folders are present
  ansible.builtin.file:
    path: '{{ user_homedir }}/{{ item }}'
    state: directory
    group: '{{ user_user }}'
    owner: '{{ user_user }}'
    mode: '0755'
  loop:
    - 'Pictures/Wallpapers'

- name: Wallpapers are present
  ansible.builtin.copy:
    src: 'wallpaper/{{ item }}'
    dest: '{{ user_homedir }}/{{ item }}'
    group: '{{ user_user }}'
    owner: '{{ user_user }}'
    mode: '0755'
  loop: '{{ desktop_wallpapers }}'

- name: Create desktop.sh
  ansible.builtin.template:
    src: desktop.sh.j2
    dest: /tmp/desktop.sh
    group: '{{ user_user }}'
    owner: '{{ user_user }}'
    mode: '0755'