---
- name: install theforeman
  hosts: "{{  lookup('env', 'ANSIBLEHOST') }}"
  become: true
  tasks:
    - name: puppet repo is present
      ansible.builtin.template:
        src: ./theforeman/puppet.list.j2
        dest: /etc/apt/sources.list.d/puppet.list
        owner: root
        group: root
        mode: '0644'
    - name: add puppet GPG key
      ansible.builtin.apt_key:
        id: 0BDDA991FD7AAC8A
        url: http://apt.puppet.com/pubkey.gpg
        state: present
    - name: theforeman repo is present
      ansible.builtin.template:
        src: ./theforeman/foreman.list.j2
        dest: /etc/apt/sources.list.d/foreman.list
        owner: root
        group: root
        mode: '0644'
    - name: theforeman GPG key is present
      ansible.builtin.apt_key:
        id: 0BDDA991FD7AAC8A
        url: https://deb.theforeman.org/pubkey.gpg
        state: present
    - name: update/upgrade OS
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 120
    - name: ca-certificates and foreman-installer are installed
      ansible.builtin.apt:
        name: '{{ item }}'
        state: present
        update_cache: yes
        cache_valid_time: 120
      loop:
        - 'ca-certificates'
        - 'foreman-installer'
